services:
  cleanarr:
    build:
      args:
        BASE_IMAGE: nvidia/cuda:12.2.2-cudnn8-runtime-ubuntu22.04
    gpus: all
    environment:
      CLEANARR_DEVICE: cuda
      CLEANARR_COMPUTE_TYPE: ${CLEANARR_GPU_COMPUTE_TYPE:-int8_float32}
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility
